// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages.proto

package polenur.primes.common;

public final class Messages {
  private Messages() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface CalcPrimesRequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 rangeStart = 1;
    /**
     * <code>required int32 rangeStart = 1;</code>
     */
    boolean hasRangeStart();
    /**
     * <code>required int32 rangeStart = 1;</code>
     */
    int getRangeStart();

    // required int32 rangeEnd = 2;
    /**
     * <code>required int32 rangeEnd = 2;</code>
     */
    boolean hasRangeEnd();
    /**
     * <code>required int32 rangeEnd = 2;</code>
     */
    int getRangeEnd();

    // optional string requestId = 3;
    /**
     * <code>optional string requestId = 3;</code>
     */
    boolean hasRequestId();
    /**
     * <code>optional string requestId = 3;</code>
     */
    java.lang.String getRequestId();
    /**
     * <code>optional string requestId = 3;</code>
     */
    com.google.protobuf.ByteString
        getRequestIdBytes();
  }
  /**
   * Protobuf type {@code polenur.primes.CalcPrimesRequest}
   */
  public static final class CalcPrimesRequest extends
      com.google.protobuf.GeneratedMessage
      implements CalcPrimesRequestOrBuilder {
    // Use CalcPrimesRequest.newBuilder() to construct.
    private CalcPrimesRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private CalcPrimesRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final CalcPrimesRequest defaultInstance;
    public static CalcPrimesRequest getDefaultInstance() {
      return defaultInstance;
    }

    public CalcPrimesRequest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private CalcPrimesRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              rangeStart_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              rangeEnd_ = input.readInt32();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              requestId_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return polenur.primes.common.Messages.internal_static_polenur_primes_CalcPrimesRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return polenur.primes.common.Messages.internal_static_polenur_primes_CalcPrimesRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              polenur.primes.common.Messages.CalcPrimesRequest.class, polenur.primes.common.Messages.CalcPrimesRequest.Builder.class);
    }

    public static com.google.protobuf.Parser<CalcPrimesRequest> PARSER =
        new com.google.protobuf.AbstractParser<CalcPrimesRequest>() {
      public CalcPrimesRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CalcPrimesRequest(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<CalcPrimesRequest> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 rangeStart = 1;
    public static final int RANGESTART_FIELD_NUMBER = 1;
    private int rangeStart_;
    /**
     * <code>required int32 rangeStart = 1;</code>
     */
    public boolean hasRangeStart() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 rangeStart = 1;</code>
     */
    public int getRangeStart() {
      return rangeStart_;
    }

    // required int32 rangeEnd = 2;
    public static final int RANGEEND_FIELD_NUMBER = 2;
    private int rangeEnd_;
    /**
     * <code>required int32 rangeEnd = 2;</code>
     */
    public boolean hasRangeEnd() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 rangeEnd = 2;</code>
     */
    public int getRangeEnd() {
      return rangeEnd_;
    }

    // optional string requestId = 3;
    public static final int REQUESTID_FIELD_NUMBER = 3;
    private java.lang.Object requestId_;
    /**
     * <code>optional string requestId = 3;</code>
     */
    public boolean hasRequestId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string requestId = 3;</code>
     */
    public java.lang.String getRequestId() {
      java.lang.Object ref = requestId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          requestId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string requestId = 3;</code>
     */
    public com.google.protobuf.ByteString
        getRequestIdBytes() {
      java.lang.Object ref = requestId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        requestId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      rangeStart_ = 0;
      rangeEnd_ = 0;
      requestId_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasRangeStart()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasRangeEnd()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, rangeStart_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, rangeEnd_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getRequestIdBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, rangeStart_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, rangeEnd_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getRequestIdBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static polenur.primes.common.Messages.CalcPrimesRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static polenur.primes.common.Messages.CalcPrimesRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static polenur.primes.common.Messages.CalcPrimesRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static polenur.primes.common.Messages.CalcPrimesRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static polenur.primes.common.Messages.CalcPrimesRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static polenur.primes.common.Messages.CalcPrimesRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static polenur.primes.common.Messages.CalcPrimesRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static polenur.primes.common.Messages.CalcPrimesRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static polenur.primes.common.Messages.CalcPrimesRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static polenur.primes.common.Messages.CalcPrimesRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(polenur.primes.common.Messages.CalcPrimesRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code polenur.primes.CalcPrimesRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements polenur.primes.common.Messages.CalcPrimesRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return polenur.primes.common.Messages.internal_static_polenur_primes_CalcPrimesRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return polenur.primes.common.Messages.internal_static_polenur_primes_CalcPrimesRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                polenur.primes.common.Messages.CalcPrimesRequest.class, polenur.primes.common.Messages.CalcPrimesRequest.Builder.class);
      }

      // Construct using polenur.primes.common.Messages.CalcPrimesRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        rangeStart_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        rangeEnd_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        requestId_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return polenur.primes.common.Messages.internal_static_polenur_primes_CalcPrimesRequest_descriptor;
      }

      public polenur.primes.common.Messages.CalcPrimesRequest getDefaultInstanceForType() {
        return polenur.primes.common.Messages.CalcPrimesRequest.getDefaultInstance();
      }

      public polenur.primes.common.Messages.CalcPrimesRequest build() {
        polenur.primes.common.Messages.CalcPrimesRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public polenur.primes.common.Messages.CalcPrimesRequest buildPartial() {
        polenur.primes.common.Messages.CalcPrimesRequest result = new polenur.primes.common.Messages.CalcPrimesRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.rangeStart_ = rangeStart_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.rangeEnd_ = rangeEnd_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.requestId_ = requestId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof polenur.primes.common.Messages.CalcPrimesRequest) {
          return mergeFrom((polenur.primes.common.Messages.CalcPrimesRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(polenur.primes.common.Messages.CalcPrimesRequest other) {
        if (other == polenur.primes.common.Messages.CalcPrimesRequest.getDefaultInstance()) return this;
        if (other.hasRangeStart()) {
          setRangeStart(other.getRangeStart());
        }
        if (other.hasRangeEnd()) {
          setRangeEnd(other.getRangeEnd());
        }
        if (other.hasRequestId()) {
          bitField0_ |= 0x00000004;
          requestId_ = other.requestId_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasRangeStart()) {
          
          return false;
        }
        if (!hasRangeEnd()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        polenur.primes.common.Messages.CalcPrimesRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (polenur.primes.common.Messages.CalcPrimesRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 rangeStart = 1;
      private int rangeStart_ ;
      /**
       * <code>required int32 rangeStart = 1;</code>
       */
      public boolean hasRangeStart() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 rangeStart = 1;</code>
       */
      public int getRangeStart() {
        return rangeStart_;
      }
      /**
       * <code>required int32 rangeStart = 1;</code>
       */
      public Builder setRangeStart(int value) {
        bitField0_ |= 0x00000001;
        rangeStart_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 rangeStart = 1;</code>
       */
      public Builder clearRangeStart() {
        bitField0_ = (bitField0_ & ~0x00000001);
        rangeStart_ = 0;
        onChanged();
        return this;
      }

      // required int32 rangeEnd = 2;
      private int rangeEnd_ ;
      /**
       * <code>required int32 rangeEnd = 2;</code>
       */
      public boolean hasRangeEnd() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 rangeEnd = 2;</code>
       */
      public int getRangeEnd() {
        return rangeEnd_;
      }
      /**
       * <code>required int32 rangeEnd = 2;</code>
       */
      public Builder setRangeEnd(int value) {
        bitField0_ |= 0x00000002;
        rangeEnd_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 rangeEnd = 2;</code>
       */
      public Builder clearRangeEnd() {
        bitField0_ = (bitField0_ & ~0x00000002);
        rangeEnd_ = 0;
        onChanged();
        return this;
      }

      // optional string requestId = 3;
      private java.lang.Object requestId_ = "";
      /**
       * <code>optional string requestId = 3;</code>
       */
      public boolean hasRequestId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string requestId = 3;</code>
       */
      public java.lang.String getRequestId() {
        java.lang.Object ref = requestId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          requestId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string requestId = 3;</code>
       */
      public com.google.protobuf.ByteString
          getRequestIdBytes() {
        java.lang.Object ref = requestId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          requestId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string requestId = 3;</code>
       */
      public Builder setRequestId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        requestId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string requestId = 3;</code>
       */
      public Builder clearRequestId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        requestId_ = getDefaultInstance().getRequestId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string requestId = 3;</code>
       */
      public Builder setRequestIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        requestId_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:polenur.primes.CalcPrimesRequest)
    }

    static {
      defaultInstance = new CalcPrimesRequest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:polenur.primes.CalcPrimesRequest)
  }

  public interface CalcPrimesReplyOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated int32 primes = 1 [packed = true];
    /**
     * <code>repeated int32 primes = 1 [packed = true];</code>
     */
    java.util.List<java.lang.Integer> getPrimesList();
    /**
     * <code>repeated int32 primes = 1 [packed = true];</code>
     */
    int getPrimesCount();
    /**
     * <code>repeated int32 primes = 1 [packed = true];</code>
     */
    int getPrimes(int index);
  }
  /**
   * Protobuf type {@code polenur.primes.CalcPrimesReply}
   */
  public static final class CalcPrimesReply extends
      com.google.protobuf.GeneratedMessage
      implements CalcPrimesReplyOrBuilder {
    // Use CalcPrimesReply.newBuilder() to construct.
    private CalcPrimesReply(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private CalcPrimesReply(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final CalcPrimesReply defaultInstance;
    public static CalcPrimesReply getDefaultInstance() {
      return defaultInstance;
    }

    public CalcPrimesReply getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private CalcPrimesReply(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                primes_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000001;
              }
              primes_.add(input.readInt32());
              break;
            }
            case 10: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001) && input.getBytesUntilLimit() > 0) {
                primes_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000001;
              }
              while (input.getBytesUntilLimit() > 0) {
                primes_.add(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          primes_ = java.util.Collections.unmodifiableList(primes_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return polenur.primes.common.Messages.internal_static_polenur_primes_CalcPrimesReply_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return polenur.primes.common.Messages.internal_static_polenur_primes_CalcPrimesReply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              polenur.primes.common.Messages.CalcPrimesReply.class, polenur.primes.common.Messages.CalcPrimesReply.Builder.class);
    }

    public static com.google.protobuf.Parser<CalcPrimesReply> PARSER =
        new com.google.protobuf.AbstractParser<CalcPrimesReply>() {
      public CalcPrimesReply parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CalcPrimesReply(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<CalcPrimesReply> getParserForType() {
      return PARSER;
    }

    // repeated int32 primes = 1 [packed = true];
    public static final int PRIMES_FIELD_NUMBER = 1;
    private java.util.List<java.lang.Integer> primes_;
    /**
     * <code>repeated int32 primes = 1 [packed = true];</code>
     */
    public java.util.List<java.lang.Integer>
        getPrimesList() {
      return primes_;
    }
    /**
     * <code>repeated int32 primes = 1 [packed = true];</code>
     */
    public int getPrimesCount() {
      return primes_.size();
    }
    /**
     * <code>repeated int32 primes = 1 [packed = true];</code>
     */
    public int getPrimes(int index) {
      return primes_.get(index);
    }
    private int primesMemoizedSerializedSize = -1;

    private void initFields() {
      primes_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (getPrimesList().size() > 0) {
        output.writeRawVarint32(10);
        output.writeRawVarint32(primesMemoizedSerializedSize);
      }
      for (int i = 0; i < primes_.size(); i++) {
        output.writeInt32NoTag(primes_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < primes_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(primes_.get(i));
        }
        size += dataSize;
        if (!getPrimesList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        primesMemoizedSerializedSize = dataSize;
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static polenur.primes.common.Messages.CalcPrimesReply parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static polenur.primes.common.Messages.CalcPrimesReply parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static polenur.primes.common.Messages.CalcPrimesReply parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static polenur.primes.common.Messages.CalcPrimesReply parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static polenur.primes.common.Messages.CalcPrimesReply parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static polenur.primes.common.Messages.CalcPrimesReply parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static polenur.primes.common.Messages.CalcPrimesReply parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static polenur.primes.common.Messages.CalcPrimesReply parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static polenur.primes.common.Messages.CalcPrimesReply parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static polenur.primes.common.Messages.CalcPrimesReply parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(polenur.primes.common.Messages.CalcPrimesReply prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code polenur.primes.CalcPrimesReply}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements polenur.primes.common.Messages.CalcPrimesReplyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return polenur.primes.common.Messages.internal_static_polenur_primes_CalcPrimesReply_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return polenur.primes.common.Messages.internal_static_polenur_primes_CalcPrimesReply_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                polenur.primes.common.Messages.CalcPrimesReply.class, polenur.primes.common.Messages.CalcPrimesReply.Builder.class);
      }

      // Construct using polenur.primes.common.Messages.CalcPrimesReply.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        primes_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return polenur.primes.common.Messages.internal_static_polenur_primes_CalcPrimesReply_descriptor;
      }

      public polenur.primes.common.Messages.CalcPrimesReply getDefaultInstanceForType() {
        return polenur.primes.common.Messages.CalcPrimesReply.getDefaultInstance();
      }

      public polenur.primes.common.Messages.CalcPrimesReply build() {
        polenur.primes.common.Messages.CalcPrimesReply result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public polenur.primes.common.Messages.CalcPrimesReply buildPartial() {
        polenur.primes.common.Messages.CalcPrimesReply result = new polenur.primes.common.Messages.CalcPrimesReply(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          primes_ = java.util.Collections.unmodifiableList(primes_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.primes_ = primes_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof polenur.primes.common.Messages.CalcPrimesReply) {
          return mergeFrom((polenur.primes.common.Messages.CalcPrimesReply)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(polenur.primes.common.Messages.CalcPrimesReply other) {
        if (other == polenur.primes.common.Messages.CalcPrimesReply.getDefaultInstance()) return this;
        if (!other.primes_.isEmpty()) {
          if (primes_.isEmpty()) {
            primes_ = other.primes_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensurePrimesIsMutable();
            primes_.addAll(other.primes_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        polenur.primes.common.Messages.CalcPrimesReply parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (polenur.primes.common.Messages.CalcPrimesReply) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated int32 primes = 1 [packed = true];
      private java.util.List<java.lang.Integer> primes_ = java.util.Collections.emptyList();
      private void ensurePrimesIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          primes_ = new java.util.ArrayList<java.lang.Integer>(primes_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated int32 primes = 1 [packed = true];</code>
       */
      public java.util.List<java.lang.Integer>
          getPrimesList() {
        return java.util.Collections.unmodifiableList(primes_);
      }
      /**
       * <code>repeated int32 primes = 1 [packed = true];</code>
       */
      public int getPrimesCount() {
        return primes_.size();
      }
      /**
       * <code>repeated int32 primes = 1 [packed = true];</code>
       */
      public int getPrimes(int index) {
        return primes_.get(index);
      }
      /**
       * <code>repeated int32 primes = 1 [packed = true];</code>
       */
      public Builder setPrimes(
          int index, int value) {
        ensurePrimesIsMutable();
        primes_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 primes = 1 [packed = true];</code>
       */
      public Builder addPrimes(int value) {
        ensurePrimesIsMutable();
        primes_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 primes = 1 [packed = true];</code>
       */
      public Builder addAllPrimes(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensurePrimesIsMutable();
        super.addAll(values, primes_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 primes = 1 [packed = true];</code>
       */
      public Builder clearPrimes() {
        primes_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:polenur.primes.CalcPrimesReply)
    }

    static {
      defaultInstance = new CalcPrimesReply(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:polenur.primes.CalcPrimesReply)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_polenur_primes_CalcPrimesRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_polenur_primes_CalcPrimesRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_polenur_primes_CalcPrimesReply_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_polenur_primes_CalcPrimesReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016messages.proto\022\016polenur.primes\"L\n\021Calc" +
      "PrimesRequest\022\022\n\nrangeStart\030\001 \002(\005\022\020\n\010ran" +
      "geEnd\030\002 \002(\005\022\021\n\trequestId\030\003 \001(\t\"%\n\017CalcPr" +
      "imesReply\022\022\n\006primes\030\001 \003(\005B\002\020\001B!\n\025polenur" +
      ".primes.commonB\010Messages"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_polenur_primes_CalcPrimesRequest_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_polenur_primes_CalcPrimesRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_polenur_primes_CalcPrimesRequest_descriptor,
              new java.lang.String[] { "RangeStart", "RangeEnd", "RequestId", });
          internal_static_polenur_primes_CalcPrimesReply_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_polenur_primes_CalcPrimesReply_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_polenur_primes_CalcPrimesReply_descriptor,
              new java.lang.String[] { "Primes", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
